# Generated by Django 5.1 on 2025-04-14 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurt', '0002_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='gas_concentration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='gas_type',
            field=models.CharField(choices=[('methane', 'Метан'), ('LPG', 'LPG'), ('CO', 'CO')], default='methane', max_length=100),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
